// form-models.js

const { Schema, model } = require("mongoose");

const formSchema = new Schema({
  //Form_no: { type: String, required: true },
  //Type_of_form: { type: String, required: true },
  createdAt: {
    type: Date,
    default: () =>
      new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }), // Automatically set to the current date/time in Indian time zone
  },
  DateTime:{type:String},
  FilledBy_Name: { type: String },
  Type_of_form: { type: String },
  Type_of_paitent: { type: String },
  Name: { type: String },
  AadhaarNumber: { type: String },
  Age: { type: String },

  Gender: { type: String },
  Contact_no: { type: String },
  Address: { type: String },
  Previous_Occupation: { type: String },
  Chief_Complaint: { type: String },
  HOPI: { type: String },
  Site: { type: String },
  PainSiteLeft: [{ type: Schema.Types.Mixed }],
  PainSiteRight: [{ type: Schema.Types.Mixed }],
  Type: { type: String },
  IndicatePain: [{ type: Schema.Types.Mixed }],
  Onset: { type: String },
  Duration: { type: String },
  Progression: { type: String },
  Aggravating_Factors: { type: String },
  Relieving_Factors: { type: String },
  Diurnal_Variation: { type: String },
  Irritability: { type: String },
  vas: { type: String },
  NRSNeck: [{ type: Schema.Types.Mixed }],
  NRSUpperBack: [{ type: Schema.Types.Mixed }],
  NRSLowBack: [{ type: Schema.Types.Mixed }],
  NRSHip: [{ type: Schema.Types.Mixed }],
  NRSKnee: [{ type: Schema.Types.Mixed }],
  NRSAnkleAndFoot: [{ type: Schema.Types.Mixed }],
  Medical_History: { type: String },
  Surgical_History: { type: String },
  Sleep: { type: String },
  Appetite: { type: String },
  Diet: { type: String },
  Bowel: { type: String },
  Bladder: { type: String },
  Menstrual_History: { type: String },
  GPLAD: { type: String },
  G1: { type: String },
  G2: { type: String },
  G3: { type: String },
  G4: { type: String },

  Height: { type: String },
  Weight: { type: String },
  BMI: { type: String },
  BP: { type: String },
  PR: { type: String },
  RR: { type: String },
  Pallor: { type: String },

  Icterus: { type: String },
  Cyanosis: { type: String },
  Clubbing: { type: String },
  Erythema: { type: String },
  Eruptinosa: { type: String },
  Lymphadenopathy: { type: String },
  Oedema: { type: String },
  PostureImage: { type: String },
  GaitImage: { type: String },

  Swelling: { type: String },
  WoundObservation: { type: String },
  Scars: { type: String },
  Tenderness: { type: String },
  Spasm: { type: String },
  Warmth: { type: String },
  SwellinG: { type: String },
  OnAuscultation: { type: String },
  MotorExamination: [{ type: Schema.Types.Mixed }],
  CervicalRange: { type: String },
  ShoulderRange: { type: String },
  ElbowRange: { type: String },
  WristRange: { type: String },
  HandRange: { type: String },
  TrunkRange: { type: String },
  HipRange: { type: String },
  KneeRange: { type: String },
  AnkleRange: { type: String },
  StrengthR: [{ type: Schema.Types.Mixed }],
  StrengthL: [{ type: Schema.Types.Mixed }],
  Tightness: [{ type: Schema.Types.Mixed }],
  VoluntaryControl: { type: String },
  Reflexes: { type: String },
  NeurogicalAssessment: [{ type: Schema.Types.Mixed }],
  Special_Tests_Positive: { type: String },
  Special_Tests_Negative: { type: String },
  Geriatric_Depression_Scale: { type: String },
  SF_36_Score: { type: String },
  Instrumental_Activity: { type: String },
  TUG: { type: String },
  KuppuSwamy_Scale: { type: String },
  Fall_Efficacy_Scale: { type: String },
  Moca_Scale_Score: { type: String },
  Activity_of_Daily_Living: { type: String },
  Deformities: [{ type: Schema.Types.Mixed }],

  LowerExtremityFunctionScale: [{ type: Schema.Types.Mixed }],
  TheOsteoporosisKnowledgeAssessmentTool: [{ type: Schema.Types.Mixed }],
  SixMinuteWalkTest: { type: String },
  Grade_of_Dyspnoea: { type: String },
  Additional_remarks: { type: String },

  // Corrected field name
});

const Form = model("Form", formSchema);
module.exports = Form;
